<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Fonts\#RtBasisBold.otf" />
    <None Remove="Resources\Fonts\#RtBasisLight.otf" />
    <None Remove="Resources\Fonts\#RtBasisMedium.otf" />
    <None Remove="Resources\Fonts\#RtBasisRegular.otf" />
    <None Remove="Resources\Images\main1.png" />
    <None Remove="Resources\Images\main2.png" />
    <None Remove="Resources\Images\main3.png" />
    <None Remove="Resources\Images\quiz1.png" />
    <None Remove="Resources\Images\quiz2.png" />
    <None Remove="Resources\Images\quiz3.png" />
    <None Remove="Resources\Images\quiz4.png" />
    <None Remove="Resources\Images\quiz5.png" />
    <None Remove="Resources\Images\quiz6.png" />
    <None Remove="Resources\Images\quiz7.png" />
    <None Remove="Resources\Images\quiz8.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Refit.HttpClientFactory" Version="7.2.1" />
    <PackageReference Include="Refit.Newtonsoft.Json" Version="7.2.1" />
    <PackageReference Include="Serilog" Version="4.1.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MainComponents">
      <HintPath>Libs\MainComponents.dll</HintPath>
    </Reference>
    <Reference Include="MvvmNavigationLib">
      <HintPath>Libs\MvvmNavigationLib.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Fonts\#RtBasisBold.otf" />
    <Resource Include="Resources\Fonts\#RtBasisLight.otf" />
    <Resource Include="Resources\Fonts\#RtBasisMedium.otf" />
    <Resource Include="Resources\Fonts\#RtBasisRegular.otf" />
    <Resource Include="Resources\Images\main1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\main2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\main3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\quiz1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\quiz2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\quiz3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\quiz4.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\quiz5.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\quiz6.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\quiz7.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\quiz8.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
